-- Insert sample missing children cases for testing
INSERT INTO missing_children (
  id,
  name,
  age,
  gender,
  last_seen_date,
  last_seen_location,
  description,
  status,
  case_number,
  contact_info,
  photo_url,
  created_at,
  updated_at
) VALUES 
(
  gen_random_uuid(),
  'Emma Johnson',
  8,
  'female',
  '2024-01-15',
  'Central Park, New York, NY',
  'Emma was last seen wearing a red jacket and blue jeans. She has brown hair in pigtails and was carrying a small backpack.',
  'active',
  'NYC-2024-001',
  'Contact NYPD Missing Persons Unit: (212) 694-7781',
  '/placeholder.svg?height=400&width=400',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Michael Chen',
  12,
  'male',
  '2024-01-20',
  'Downtown Seattle, WA',
  'Michael was last seen after school wearing his school uniform. He has black hair and glasses.',
  'active',
  'SEA-2024-002',
  'Contact Seattle Police: (206) 625-5011',
  '/placeholder.svg?height=400&width=400',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Sofia Rodriguez',
  6,
  'female',
  '2024-01-25',
  'Miami Beach, FL',
  'Sofia was last seen at the beach wearing a pink swimsuit. She has long dark hair and was with her family.',
  'active',
  'MIA-2024-003',
  'Contact Miami-Dade Police: (305) 471-2400',
  '/placeholder.svg?height=400&width=400',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'David Thompson',
  10,
  'male',
  '2024-01-18',
  'Chicago, IL',
  'David was last seen near his school. He was wearing a blue hoodie and carrying a basketball.',
  'active',
  'CHI-2024-004',
  'Contact Chicago Police: (312) 746-6000',
  '/placeholder.svg?height=400&width=400',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Aisha Patel',
  9,
  'female',
  '2024-01-22',
  'Los Angeles, CA',
  'Aisha was last seen wearing a yellow dress. She has black hair in braids and was walking home from school.',
  'active',
  'LA-2024-005',
  'Contact LAPD: (213) 486-6000',
  '/placeholder.svg?height=400&width=400',
  NOW(),
  NOW()
);
